# Generated by Django 3.0.3 on 2020-05-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-date',)},
        ),
    ]
