# Generated by Django 3.0.3 on 2020-05-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0003_uploadedassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedassignment',
            options={'ordering': ('-uploaded_date',)},
        ),
        migrations.AlterField(
            model_name='uploadedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
